<?php

namespace Database\Seeders;

use App\Models\Doctor;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DoctorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Xóa dữ liệu cũ (không dùng truncate vì có foreign key)
        // Xóa các bản ghi liên quan trước
        $doctorIds = DB::table('doctors')->pluck('id');
        if ($doctorIds->isNotEmpty()) {
            DB::table('doctor_messages')->whereIn('doctor_id', $doctorIds)->delete();
            DB::table('doctor_reviews')->whereIn('doctor_id', $doctorIds)->delete();
            DB::table('consultations')->whereNotNull('doctor_id')->whereIn('doctor_id', $doctorIds)->update(['doctor_id' => null]);
        }
        
        // Sau đó xóa doctors
        Doctor::query()->delete();
        
        $doctors = [
            [
                'name' => 'BS. Nguyễn Thị Hương',
                'specialization' => 'Bác sĩ Tim mạch',
                'email' => 'huong.nguyen@healthcare.vn',
                'phone' => '+84-24-1234-5678',
                'bio' => 'BS. Nguyễn Thị Hương là bác sĩ tim mạch được chứng nhận với hơn 15 năm kinh nghiệm trong điều trị các bệnh tim mạch. Bà chuyên về tim mạch phòng ngừa, quản lý suy tim và can thiệp tim mạch. BS. Hương cam kết cung cấp dịch vụ chăm sóc cá nhân hóa và giúp bệnh nhân đạt được sức khỏe tim mạch tối ưu.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Hà Nội',
                'certifications' => ['Chứng nhận Bác sĩ Tim mạch', 'Hiệp hội Tim mạch Việt Nam'],
                'specialties' => ['Tim mạch phòng ngừa', 'Quản lý suy tim', 'Can thiệp tim mạch', 'Phục hồi chức năng tim'],
                'hospital_affiliations' => ['Bệnh viện Tim Hà Nội', 'Trung tâm Tim mạch'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 15,
                'consultation_fee' => 500000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 8:00 - 17:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Trần Văn Minh',
                'specialization' => 'Bác sĩ Đa khoa',
                'email' => 'minh.tran@healthcare.vn',
                'phone' => '+84-24-1234-5679',
                'bio' => 'BS. Trần Văn Minh là bác sĩ đa khoa tận tâm với 12 năm kinh nghiệm trong y học gia đình. Ông cung cấp dịch vụ chăm sóc sức khỏe ban đầu toàn diện cho bệnh nhân ở mọi lứa tuổi, tập trung vào chăm sóc phòng ngừa, quản lý bệnh mãn tính và nâng cao sức khỏe.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Dược TP.HCM',
                'certifications' => ['Chứng nhận Y học Gia đình', 'Hội Y học Gia đình Việt Nam'],
                'specialties' => ['Y học Gia đình', 'Chăm sóc Phòng ngừa', 'Quản lý Bệnh Mãn tính', 'Nâng cao Sức khỏe'],
                'hospital_affiliations' => ['Trung tâm Y tế Cộng đồng', 'Phòng khám Gia đình'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh', 'Tiếng Trung'],
                'years_of_experience' => 12,
                'consultation_fee' => 300000.00,
                'available_hours' => 'Thứ 2 - Thứ 7: 7:00 - 18:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Lê Thị Mai',
                'specialization' => 'Bác sĩ Da liễu',
                'email' => 'mai.le@healthcare.vn',
                'phone' => '+84-24-1234-5680',
                'bio' => 'BS. Lê Thị Mai là bác sĩ da liễu được chứng nhận chuyên về da liễu y học và thẩm mỹ. Với 10 năm kinh nghiệm, bà điều trị nhiều tình trạng da khác nhau bao gồm mụn trứng cá, chàm, vảy nến và ung thư da. Bà cũng cung cấp các thủ thuật thẩm mỹ và điều trị chống lão hóa.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Hà Nội',
                'certifications' => ['Chứng nhận Bác sĩ Da liễu', 'Hội Da liễu Việt Nam'],
                'specialties' => ['Da liễu Y học', 'Da liễu Thẩm mỹ', 'Điều trị Ung thư Da', 'Điều trị Chống lão hóa'],
                'hospital_affiliations' => ['Trung tâm Chăm sóc Da', 'Phòng khám Da liễu'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 10,
                'consultation_fee' => 400000.00,
                'available_hours' => 'Thứ 3 - Thứ 6: 9:00 - 18:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Phạm Văn Đức',
                'specialization' => 'Bác sĩ Nhi khoa',
                'email' => 'duc.pham@healthcare.vn',
                'phone' => '+84-24-1234-5681',
                'bio' => 'BS. Phạm Văn Đức là bác sĩ nhi khoa giàu kinh nghiệm với 18 năm phục vụ tận tâm cho sức khỏe trẻ em. Ông chuyên về chăm sóc nhi khoa từ sơ sinh đến tuổi vị thành niên, tập trung vào tăng trưởng và phát triển, tiêm chủng và điều trị các bệnh ở trẻ em.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Hà Nội',
                'certifications' => ['Chứng nhận Bác sĩ Nhi khoa', 'Hội Nhi khoa Việt Nam'],
                'specialties' => ['Chăm sóc Nhi khoa', 'Phát triển Trẻ em', 'Tiêm chủng', 'Y học Vị thành niên'],
                'hospital_affiliations' => ['Bệnh viện Nhi Trung ương', 'Trung tâm Chăm sóc Nhi'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 18,
                'consultation_fee' => 350000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 8:00 - 17:00, Thứ 7: 8:00 - 12:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Hoàng Thị Lan',
                'specialization' => 'Bác sĩ Thần kinh',
                'email' => 'lan.hoang@healthcare.vn',
                'phone' => '+84-24-1234-5682',
                'bio' => 'BS. Hoàng Thị Lan là bác sĩ thần kinh được chứng nhận với 14 năm kinh nghiệm trong chẩn đoán và điều trị các rối loạn thần kinh. Bà chuyên về đau đầu, động kinh, rối loạn vận động và bệnh thoái hóa thần kinh. BS. Lan được biết đến với cách tiếp cận đồng cảm và đánh giá chẩn đoán kỹ lưỡng.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Dược TP.HCM',
                'certifications' => ['Chứng nhận Bác sĩ Thần kinh', 'Hội Thần kinh Việt Nam'],
                'specialties' => ['Quản lý Đau đầu', 'Động kinh', 'Rối loạn Vận động', 'Bệnh Thoái hóa Thần kinh'],
                'hospital_affiliations' => ['Trung tâm Thần kinh', 'Viện Sức khỏe Não'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 14,
                'consultation_fee' => 600000.00,
                'available_hours' => 'Thứ 2 - Thứ 5: 9:00 - 17:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Nguyễn Văn Hùng',
                'specialization' => 'Bác sĩ Chấn thương Chỉnh hình',
                'email' => 'hung.nguyen@healthcare.vn',
                'phone' => '+84-24-1234-5683',
                'bio' => 'BS. Nguyễn Văn Hùng là bác sĩ phẫu thuật chỉnh hình nổi tiếng với 20 năm kinh nghiệm trong điều trị các tình trạng cơ xương khớp. Ông chuyên về thay khớp, y học thể thao và phẫu thuật chấn thương. BS. Hùng cam kết giúp bệnh nhân lấy lại khả năng vận động và trở lại lối sống năng động.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Hà Nội',
                'certifications' => ['Chứng nhận Bác sĩ Phẫu thuật Chỉnh hình', 'Hội Chấn thương Chỉnh hình Việt Nam'],
                'specialties' => ['Thay Khớp', 'Y học Thể thao', 'Phẫu thuật Chấn thương', 'Phẫu thuật Nội soi'],
                'hospital_affiliations' => ['Trung tâm Chỉnh hình', 'Phòng khám Y học Thể thao'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 20,
                'consultation_fee' => 700000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 8:00 - 18:00',
                'status' => 'active',
            ],
            // Thêm 20 bác sĩ mới
            [
                'name' => 'BS. Võ Thị Hoa',
                'specialization' => 'Bác sĩ Sản phụ khoa',
                'email' => 'hoa.vo@healthcare.vn',
                'phone' => '+84-24-1234-5684',
                'bio' => 'BS. Võ Thị Hoa là bác sĩ sản phụ khoa với 16 năm kinh nghiệm trong chăm sóc sức khỏe phụ nữ. Bà chuyên về sản khoa, phụ khoa và hỗ trợ sinh sản.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Hà Nội',
                'certifications' => ['Chứng nhận Bác sĩ Sản phụ khoa', 'Hội Sản phụ khoa Việt Nam'],
                'specialties' => ['Sản khoa', 'Phụ khoa', 'Hỗ trợ Sinh sản', 'Sức khỏe Phụ nữ'],
                'hospital_affiliations' => ['Bệnh viện Phụ sản Trung ương', 'Phòng khám Sản phụ khoa'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 16,
                'consultation_fee' => 450000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 8:00 - 17:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Đỗ Văn Long',
                'specialization' => 'Bác sĩ Tiêu hóa',
                'email' => 'long.do@healthcare.vn',
                'phone' => '+84-24-1234-5685',
                'bio' => 'BS. Đỗ Văn Long là bác sĩ tiêu hóa với 13 năm kinh nghiệm trong chẩn đoán và điều trị các bệnh về đường tiêu hóa. Ông chuyên về nội soi tiêu hóa và điều trị bệnh gan.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Dược TP.HCM',
                'certifications' => ['Chứng nhận Bác sĩ Tiêu hóa', 'Hội Tiêu hóa Việt Nam'],
                'specialties' => ['Nội soi Tiêu hóa', 'Bệnh Gan', 'Bệnh Dạ dày', 'Bệnh Đại tràng'],
                'hospital_affiliations' => ['Bệnh viện Bạch Mai', 'Trung tâm Tiêu hóa'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 13,
                'consultation_fee' => 550000.00,
                'available_hours' => 'Thứ 2 - Thứ 5: 9:00 - 17:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Phan Thị Linh',
                'specialization' => 'Bác sĩ Nội tiết',
                'email' => 'linh.phan@healthcare.vn',
                'phone' => '+84-24-1234-5686',
                'bio' => 'BS. Phan Thị Linh là bác sĩ nội tiết với 11 năm kinh nghiệm trong điều trị các rối loạn nội tiết. Bà chuyên về đái tháo đường, bệnh tuyến giáp và rối loạn chuyển hóa.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Hà Nội',
                'certifications' => ['Chứng nhận Bác sĩ Nội tiết', 'Hội Nội tiết Việt Nam'],
                'specialties' => ['Đái tháo đường', 'Bệnh Tuyến giáp', 'Rối loạn Chuyển hóa', 'Béo phì'],
                'hospital_affiliations' => ['Bệnh viện Nội tiết Trung ương', 'Phòng khám Nội tiết'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 11,
                'consultation_fee' => 500000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 8:00 - 16:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Bùi Văn Tuấn',
                'specialization' => 'Bác sĩ Hô hấp',
                'email' => 'tuan.bui@healthcare.vn',
                'phone' => '+84-24-1234-5687',
                'bio' => 'BS. Bùi Văn Tuấn là bác sĩ hô hấp với 14 năm kinh nghiệm trong điều trị các bệnh về phổi và đường hô hấp. Ông chuyên về hen suyễn, COPD và bệnh phổi tắc nghẽn.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Dược TP.HCM',
                'certifications' => ['Chứng nhận Bác sĩ Hô hấp', 'Hội Hô hấp Việt Nam'],
                'specialties' => ['Hen suyễn', 'COPD', 'Bệnh Phổi', 'Nội soi Phế quản'],
                'hospital_affiliations' => ['Bệnh viện Phổi Trung ương', 'Trung tâm Hô hấp'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 14,
                'consultation_fee' => 480000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 8:00 - 17:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Lý Thị Nga',
                'specialization' => 'Bác sĩ Mắt',
                'email' => 'nga.ly@healthcare.vn',
                'phone' => '+84-24-1234-5688',
                'bio' => 'BS. Lý Thị Nga là bác sĩ mắt với 12 năm kinh nghiệm trong chẩn đoán và điều trị các bệnh về mắt. Bà chuyên về phẫu thuật đục thủy tinh thể, bệnh võng mạc và tật khúc xạ.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Hà Nội',
                'certifications' => ['Chứng nhận Bác sĩ Mắt', 'Hội Nhãn khoa Việt Nam'],
                'specialties' => ['Phẫu thuật Đục thủy tinh thể', 'Bệnh Võng mạc', 'Tật Khúc xạ', 'Bệnh Glaucoma'],
                'hospital_affiliations' => ['Bệnh viện Mắt Trung ương', 'Phòng khám Mắt'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 12,
                'consultation_fee' => 420000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 8:00 - 17:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Trịnh Văn Quang',
                'specialization' => 'Bác sĩ Tai Mũi Họng',
                'email' => 'quang.trinh@healthcare.vn',
                'phone' => '+84-24-1234-5689',
                'bio' => 'BS. Trịnh Văn Quang là bác sĩ tai mũi họng với 15 năm kinh nghiệm trong điều trị các bệnh về tai, mũi và họng. Ông chuyên về phẫu thuật tai mũi họng và điều trị viêm xoang.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Dược TP.HCM',
                'certifications' => ['Chứng nhận Bác sĩ Tai Mũi Họng', 'Hội Tai Mũi Họng Việt Nam'],
                'specialties' => ['Phẫu thuật Tai Mũi Họng', 'Viêm Xoang', 'Bệnh Tai', 'Bệnh Họng'],
                'hospital_affiliations' => ['Bệnh viện Tai Mũi Họng Trung ương', 'Phòng khám TMH'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 15,
                'consultation_fee' => 400000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 8:00 - 17:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Đinh Thị Lan',
                'specialization' => 'Bác sĩ Tâm thần',
                'email' => 'lan.dinh@healthcare.vn',
                'phone' => '+84-24-1234-5690',
                'bio' => 'BS. Đinh Thị Lan là bác sĩ tâm thần với 13 năm kinh nghiệm trong điều trị các rối loạn tâm thần. Bà chuyên về trầm cảm, lo âu và rối loạn tâm thần khác.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Hà Nội',
                'certifications' => ['Chứng nhận Bác sĩ Tâm thần', 'Hội Tâm thần Việt Nam'],
                'specialties' => ['Trầm cảm', 'Rối loạn Lo âu', 'Rối loạn Tâm thần', 'Tư vấn Tâm lý'],
                'hospital_affiliations' => ['Bệnh viện Tâm thần Trung ương', 'Phòng khám Tâm thần'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 13,
                'consultation_fee' => 450000.00,
                'available_hours' => 'Thứ 2 - Thứ 5: 9:00 - 17:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Vũ Văn Hải',
                'specialization' => 'Bác sĩ Ung bướu',
                'email' => 'hai.vu@healthcare.vn',
                'phone' => '+84-24-1234-5691',
                'bio' => 'BS. Vũ Văn Hải là bác sĩ ung bướu với 17 năm kinh nghiệm trong điều trị ung thư. Ông chuyên về hóa trị, xạ trị và điều trị đa mô thức cho bệnh nhân ung thư.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Dược TP.HCM',
                'certifications' => ['Chứng nhận Bác sĩ Ung bướu', 'Hội Ung bướu Việt Nam'],
                'specialties' => ['Hóa trị', 'Xạ trị', 'Điều trị Đa mô thức', 'Chăm sóc Giảm nhẹ'],
                'hospital_affiliations' => ['Bệnh viện K', 'Trung tâm Ung bướu'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 17,
                'consultation_fee' => 650000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 8:00 - 17:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Ngô Thị Hạnh',
                'specialization' => 'Bác sĩ Thận - Tiết niệu',
                'email' => 'hanh.ngo@healthcare.vn',
                'phone' => '+84-24-1234-5692',
                'bio' => 'BS. Ngô Thị Hạnh là bác sĩ thận - tiết niệu với 14 năm kinh nghiệm trong điều trị các bệnh về thận và đường tiết niệu. Bà chuyên về lọc máu, ghép thận và sỏi tiết niệu.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Hà Nội',
                'certifications' => ['Chứng nhận Bác sĩ Thận - Tiết niệu', 'Hội Thận học Việt Nam'],
                'specialties' => ['Lọc máu', 'Ghép Thận', 'Sỏi Tiết niệu', 'Bệnh Thận'],
                'hospital_affiliations' => ['Bệnh viện Bạch Mai', 'Trung tâm Thận học'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 14,
                'consultation_fee' => 550000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 8:00 - 17:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Cao Văn Sơn',
                'specialization' => 'Bác sĩ Ngoại tổng quát',
                'email' => 'son.cao@healthcare.vn',
                'phone' => '+84-24-1234-5693',
                'bio' => 'BS. Cao Văn Sơn là bác sĩ ngoại tổng quát với 19 năm kinh nghiệm trong phẫu thuật. Ông chuyên về phẫu thuật tổng quát, phẫu thuật nội soi và cấp cứu ngoại khoa.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Dược TP.HCM',
                'certifications' => ['Chứng nhận Bác sĩ Ngoại khoa', 'Hội Ngoại khoa Việt Nam'],
                'specialties' => ['Phẫu thuật Tổng quát', 'Phẫu thuật Nội soi', 'Cấp cứu Ngoại khoa', 'Phẫu thuật Tiêu hóa'],
                'hospital_affiliations' => ['Bệnh viện Chợ Rẫy', 'Trung tâm Ngoại khoa'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 19,
                'consultation_fee' => 600000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 8:00 - 18:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Dương Thị Thảo',
                'specialization' => 'Bác sĩ Y học Cổ truyền',
                'email' => 'thao.duong@healthcare.vn',
                'phone' => '+84-24-1234-5694',
                'bio' => 'BS. Dương Thị Thảo là bác sĩ y học cổ truyền với 12 năm kinh nghiệm trong điều trị bằng phương pháp Đông y. Bà chuyên về châm cứu, bấm huyệt và thuốc Đông y.',
                'education' => 'Tiến sĩ Y học Cổ truyền, Đại học Y Hà Nội',
                'certifications' => ['Chứng nhận Bác sĩ Y học Cổ truyền', 'Hội Y học Cổ truyền Việt Nam'],
                'specialties' => ['Châm cứu', 'Bấm huyệt', 'Thuốc Đông y', 'Xoa bóp'],
                'hospital_affiliations' => ['Bệnh viện Y học Cổ truyền Trung ương', 'Phòng khám Đông y'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh', 'Tiếng Trung'],
                'years_of_experience' => 12,
                'consultation_fee' => 350000.00,
                'available_hours' => 'Thứ 2 - Thứ 7: 8:00 - 17:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Lưu Văn Nam',
                'specialization' => 'Bác sĩ Gây mê Hồi sức',
                'email' => 'nam.luu@healthcare.vn',
                'phone' => '+84-24-1234-5695',
                'bio' => 'BS. Lưu Văn Nam là bác sĩ gây mê hồi sức với 16 năm kinh nghiệm trong gây mê và hồi sức. Ông chuyên về gây mê phẫu thuật, hồi sức cấp cứu và chăm sóc đặc biệt.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Hà Nội',
                'certifications' => ['Chứng nhận Bác sĩ Gây mê Hồi sức', 'Hội Gây mê Hồi sức Việt Nam'],
                'specialties' => ['Gây mê Phẫu thuật', 'Hồi sức Cấp cứu', 'Chăm sóc Đặc biệt', 'Giảm đau Sau mổ'],
                'hospital_affiliations' => ['Bệnh viện Bạch Mai', 'Trung tâm Gây mê Hồi sức'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 16,
                'consultation_fee' => 580000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 8:00 - 17:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Tạ Thị Hương',
                'specialization' => 'Bác sĩ Dị ứng - Miễn dịch',
                'email' => 'huong.ta@healthcare.vn',
                'phone' => '+84-24-1234-5696',
                'bio' => 'BS. Tạ Thị Hương là bác sĩ dị ứng - miễn dịch với 11 năm kinh nghiệm trong điều trị các bệnh dị ứng và rối loạn miễn dịch. Bà chuyên về hen suyễn, viêm mũi dị ứng và dị ứng thực phẩm.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Dược TP.HCM',
                'certifications' => ['Chứng nhận Bác sĩ Dị ứng - Miễn dịch', 'Hội Dị ứng Miễn dịch Việt Nam'],
                'specialties' => ['Dị ứng', 'Hen suyễn', 'Viêm mũi Dị ứng', 'Rối loạn Miễn dịch'],
                'hospital_affiliations' => ['Bệnh viện Bạch Mai', 'Phòng khám Dị ứng'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 11,
                'consultation_fee' => 450000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 8:00 - 16:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Hồ Văn Đạt',
                'specialization' => 'Bác sĩ Phẫu thuật Thẩm mỹ',
                'email' => 'dat.ho@healthcare.vn',
                'phone' => '+84-24-1234-5697',
                'bio' => 'BS. Hồ Văn Đạt là bác sĩ phẫu thuật thẩm mỹ với 13 năm kinh nghiệm trong phẫu thuật thẩm mỹ và tái tạo. Ông chuyên về phẫu thuật nâng mũi, căng da mặt và phẫu thuật thẩm mỹ cơ thể.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Dược TP.HCM',
                'certifications' => ['Chứng nhận Bác sĩ Phẫu thuật Thẩm mỹ', 'Hội Phẫu thuật Thẩm mỹ Việt Nam'],
                'specialties' => ['Phẫu thuật Nâng mũi', 'Căng da Mặt', 'Phẫu thuật Thẩm mỹ Cơ thể', 'Tái tạo'],
                'hospital_affiliations' => ['Bệnh viện Thẩm mỹ', 'Phòng khám Thẩm mỹ'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 13,
                'consultation_fee' => 800000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 9:00 - 18:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Phùng Thị Mai',
                'specialization' => 'Bác sĩ Huyết học',
                'email' => 'mai.phung@healthcare.vn',
                'phone' => '+84-24-1234-5698',
                'bio' => 'BS. Phùng Thị Mai là bác sĩ huyết học với 15 năm kinh nghiệm trong điều trị các bệnh về máu. Bà chuyên về bệnh bạch cầu, thiếu máu và rối loạn đông máu.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Hà Nội',
                'certifications' => ['Chứng nhận Bác sĩ Huyết học', 'Hội Huyết học Việt Nam'],
                'specialties' => ['Bệnh Bạch cầu', 'Thiếu máu', 'Rối loạn Đông máu', 'Truyền máu'],
                'hospital_affiliations' => ['Bệnh viện Huyết học Truyền máu Trung ương', 'Trung tâm Huyết học'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 15,
                'consultation_fee' => 600000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 8:00 - 17:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Đặng Văn Thành',
                'specialization' => 'Bác sĩ Chấn thương',
                'email' => 'thanh.dang@healthcare.vn',
                'phone' => '+84-24-1234-5699',
                'bio' => 'BS. Đặng Văn Thành là bác sĩ chấn thương với 18 năm kinh nghiệm trong điều trị chấn thương. Ông chuyên về chấn thương thể thao, chấn thương giao thông và cấp cứu chấn thương.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Dược TP.HCM',
                'certifications' => ['Chứng nhận Bác sĩ Chấn thương', 'Hội Chấn thương Việt Nam'],
                'specialties' => ['Chấn thương Thể thao', 'Chấn thương Giao thông', 'Cấp cứu Chấn thương', 'Phục hồi Chức năng'],
                'hospital_affiliations' => ['Bệnh viện Chấn thương Chỉnh hình', 'Trung tâm Chấn thương'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 18,
                'consultation_fee' => 650000.00,
                'available_hours' => 'Thứ 2 - Thứ 7: 8:00 - 18:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Vương Thị Hồng',
                'specialization' => 'Bác sĩ Lão khoa',
                'email' => 'hong.vuong@healthcare.vn',
                'phone' => '+84-24-1234-5700',
                'bio' => 'BS. Vương Thị Hồng là bác sĩ lão khoa với 14 năm kinh nghiệm trong chăm sóc sức khỏe người cao tuổi. Bà chuyên về bệnh lão khoa, chăm sóc giảm nhẹ và quản lý đa bệnh lý.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Hà Nội',
                'certifications' => ['Chứng nhận Bác sĩ Lão khoa', 'Hội Lão khoa Việt Nam'],
                'specialties' => ['Bệnh Lão khoa', 'Chăm sóc Giảm nhẹ', 'Quản lý Đa bệnh lý', 'Sức khỏe Người cao tuổi'],
                'hospital_affiliations' => ['Bệnh viện Lão khoa', 'Trung tâm Chăm sóc Người cao tuổi'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 14,
                'consultation_fee' => 400000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 8:00 - 16:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Lâm Văn Hùng',
                'specialization' => 'Bác sĩ Phục hồi Chức năng',
                'email' => 'hung.lam@healthcare.vn',
                'phone' => '+84-24-1234-5701',
                'bio' => 'BS. Lâm Văn Hùng là bác sĩ phục hồi chức năng với 12 năm kinh nghiệm trong phục hồi chức năng. Ông chuyên về vật lý trị liệu, phục hồi sau chấn thương và phục hồi thần kinh.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Dược TP.HCM',
                'certifications' => ['Chứng nhận Bác sĩ Phục hồi Chức năng', 'Hội Phục hồi Chức năng Việt Nam'],
                'specialties' => ['Vật lý Trị liệu', 'Phục hồi Sau chấn thương', 'Phục hồi Thần kinh', 'Phục hồi Vận động'],
                'hospital_affiliations' => ['Bệnh viện Phục hồi Chức năng', 'Trung tâm Vật lý Trị liệu'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 12,
                'consultation_fee' => 380000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 8:00 - 17:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Tôn Thị Lan',
                'specialization' => 'Bác sĩ Truyền nhiễm',
                'email' => 'lan.ton@healthcare.vn',
                'phone' => '+84-24-1234-5702',
                'bio' => 'BS. Tôn Thị Lan là bác sĩ truyền nhiễm với 16 năm kinh nghiệm trong điều trị các bệnh truyền nhiễm. Bà chuyên về sốt xuất huyết, viêm gan và các bệnh truyền nhiễm khác.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Hà Nội',
                'certifications' => ['Chứng nhận Bác sĩ Truyền nhiễm', 'Hội Truyền nhiễm Việt Nam'],
                'specialties' => ['Sốt Xuất huyết', 'Viêm Gan', 'Bệnh Truyền nhiễm', 'Tiêm chủng'],
                'hospital_affiliations' => ['Bệnh viện Bệnh Nhiệt đới Trung ương', 'Trung tâm Truyền nhiễm'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 16,
                'consultation_fee' => 520000.00,
                'available_hours' => 'Thứ 2 - Thứ 6: 8:00 - 17:00',
                'status' => 'active',
            ],
            [
                'name' => 'BS. Chu Văn Đức',
                'specialization' => 'Bác sĩ Cấp cứu',
                'email' => 'duc.chu@healthcare.vn',
                'phone' => '+84-24-1234-5703',
                'bio' => 'BS. Chu Văn Đức là bác sĩ cấp cứu với 17 năm kinh nghiệm trong cấp cứu và hồi sức. Ông chuyên về cấp cứu tim mạch, cấp cứu chấn thương và hồi sức tích cực.',
                'education' => 'Tiến sĩ Y khoa, Đại học Y Dược TP.HCM',
                'certifications' => ['Chứng nhận Bác sĩ Cấp cứu', 'Hội Cấp cứu Việt Nam'],
                'specialties' => ['Cấp cứu Tim mạch', 'Cấp cứu Chấn thương', 'Hồi sức Tích cực', 'Cấp cứu Nhi khoa'],
                'hospital_affiliations' => ['Bệnh viện Cấp cứu', 'Trung tâm Cấp cứu'],
                'languages' => ['Tiếng Việt', 'Tiếng Anh'],
                'years_of_experience' => 17,
                'consultation_fee' => 580000.00,
                'available_hours' => '24/7 (Cấp cứu)',
                'status' => 'active',
            ],
        ];

        foreach ($doctors as $doctorData) {
            // Tạo user account cho bác sĩ
            $user = User::firstOrCreate(
                ['email' => $doctorData['email']],
                [
                    'name' => $doctorData['name'],
                    'password' => Hash::make('doctor123'), // Password mặc định
                    'role' => 'doctor',
                    'status' => 'active',
                    'phone' => $doctorData['phone'],
                ]
            );
            
            // Tạo doctor record
            Doctor::create($doctorData);
        }
    }
}



